local h = require("tests.helpers")
vim.opt.runtimepath:prepend(h.dependency_root("UX_FOUNDATION_ROOT", "UX-foundation.nvim"))
local foundation = require("ux_foundation")
local components = require("ux_chrome.components")
local api = vim.api
local property = "ux.chrome.components/navigation/padding/value"
local function reset()
  assert(components.teardown())
  foundation._reset_for_tests()
  foundation.setup({ load_active = false })
end
local function window(id)
  local buf = api.nvim_create_buf(false, true)
  local win = api.nvim_open_win(buf, false, { relative = "editor", row = 1, col = 1, width = 30, height = 4 })
  local count, fail = 0, false
  local render
  render = function()
    count = count + 1
    if fail then fail = false; error("synthetic consumer failure") end
    local context = components.context({ id = id, window = win, redraw = render })
    local header = context:format({ kind = "header", prefix = "▾", text = "Sessions", count = 1 })
    local row = context:format({ text = "example" })
    local empty = context:format({ kind = "empty", text = "(none)" })
    api.nvim_buf_set_lines(buf, 0, -1, false, { header, row, empty })
  end
  render()
  return win, buf, function() fail = true end, function() return count end
end

h.test("components truncate display cells and preserve combining characters", function()
  h.equal(components.truncate("abcdef", 0), "")
  h.equal(components.truncate("abcdef", 1), "…")
  h.equal(components.truncate("abcdef", 3, "clip"), "abc")
  h.equal(components.truncate("界界界", 4), "界…")
  h.equal(components.truncate("ééé", 2), "é…")
  h.equal(components.truncate("a\nb\tc", 20), "a b c")
  h.equal(components.truncate("abcdef", 1, "none"), "abcdef")
end)

h.test("component layout, highlight offsets, colors and invalid values", function()
  reset()
  local context = components.context({ id = "test.layout", width = 30 })
  local row, span = context:format({ text = "界é", prefix = "●", depth = 2 })
  h.equal(row, "     ● 界é")
  h.equal(span.start, #"     ● ")
  h.equal(span.finish, #row)
  local tx = assert(foundation.begin_transaction())
  h.equal(tx:stage(property, 9), false)
  assert(tx:stage("ux.chrome.components/navigation/indent/value", 4))
  assert(tx:stage("ux.chrome.components/navigation/gap/value", 0))
  context = components.context({ id = "test.layout", width = 30 })
  h.equal(context:format({ text = "item" }), "     item")
  h.equal(context:format({ kind = "header", text = "Items", count = 2 }), " Items(2)")
  assert(tx:stage("ux.chrome.components.appearance/appearance/header/foreground", { kind = "rgb", value = "#123456" }))
  h.equal(api.nvim_get_hl(0, { name = "UXChromeComponentHeader", link = false }).fg, 0x123456)
  assert(tx:revert()); assert(tx:commit())
  h.equal(api.nvim_get_hl(0, { name = "UXChromeComponentHeader", link = true }).link, "Title")
end)

h.test("shared live updates preserve selection, support overrides, rollback and reopen", function()
  reset()
  local a, abuf, fail = window("test.agents")
  local b, bbuf = window("test.git")
  api.nvim_win_set_cursor(a, { 2, 4 })
  local original = api.nvim_buf_get_lines(abuf, 0, -1, false)
  local tx = assert(foundation.begin_transaction())
  assert(tx:stage(property, 3))
  h.equal(api.nvim_buf_get_lines(abuf, 0, 1, false)[1], "   ▾ Sessions  (1)")
  h.equal(api.nvim_buf_get_lines(bbuf, 0, 1, false)[1], "   ▾ Sessions  (1)")
  h.equal(api.nvim_win_get_cursor(a), { 2, 4 })
  assert(tx:stage("ux.chrome.component.test.git/navigation/padding/value", 0))
  h.equal(api.nvim_buf_get_lines(bbuf, 0, 1, false)[1], "▾ Sessions  (1)")
  assert(tx:undo())
  h.equal(api.nvim_buf_get_lines(bbuf, 0, 1, false)[1], "   ▾ Sessions  (1)")
  fail()
  local ok = tx:stage(property, 7)
  h.equal(ok, false)
  h.equal(components.inspect("test.agents").padding, 3)
  h.equal(api.nvim_buf_get_lines(abuf, 0, 1, false)[1], "   ▾ Sessions  (1)")
  assert(tx:revert()); assert(tx:commit())
  h.equal(api.nvim_buf_get_lines(abuf, 0, -1, false), original)
  api.nvim_win_close(a, true); api.nvim_win_close(b, true)
  local c, cbuf = window("test.agents")
  h.equal(api.nvim_buf_get_lines(cbuf, 0, -1, false), original)
  api.nvim_win_close(c, true)
end)

h.test("component profiles load before reopening and discard stale window callbacks", function()
  reset()
  local win, buf, _, count = window("test.saved")
  local tx = assert(foundation.begin_transaction())
  assert(tx:stage(property, 4)); assert(tx:save())
  api.nvim_win_set_buf(win, api.nvim_create_buf(false, true))
  local previous = count()
  local next_tx = assert(foundation.begin_transaction())
  assert(next_tx:stage(property, 5)); assert(next_tx:revert()); assert(next_tx:commit())
  h.equal(count(), previous)
  h.equal(api.nvim_buf_get_lines(buf, 0, 1, false)[1], "    ▾ Sessions  (1)")
  api.nvim_win_close(win, true)
  assert(components.teardown()); foundation._reset_for_tests()
  foundation.setup({ load_active = true })
  local reopened, reopened_buf = window("test.saved")
  h.equal(api.nvim_buf_get_lines(reopened_buf, 0, 1, false)[1], "    ▾ Sessions  (1)")
  h.equal(package.loaded.ux_styling, nil)
  api.nvim_win_close(reopened, true)
  assert(components.teardown())
end)

h.finish()
