local h = require("tests.helpers")
vim.opt.runtimepath:prepend(h.dependency_root("UX_FOUNDATION_ROOT", "UX-foundation.nvim"))
local foundation = require("ux_foundation")
local drawer = require("ux_chrome.drawer")
local panes = require("ux_chrome.panes")
local api = vim.api
local function flush() vim.wait(30, function() return false end) end
local function reset()
  drawer.teardown()
  panes.teardown()
  vim.cmd("silent! tabonly! | silent! only!")
  foundation._reset_for_tests()
  foundation.setup({ load_active = false })
end
local function lines() return api.nvim_buf_get_lines(drawer.inspect().buffer, 0, -1, false) end
local function log(count)
  local result = {}
  for i = 1, count do result[i] = "line " .. i end
  return result
end

h.test("drawer registration validates inputs and publishing is atomic and bounded", function()
  reset()
  h.equal(pcall(drawer.register, { id = "bad..id" }), false)
  h.equal(pcall(drawer.register, { id = "test.log", limit = 0 }), false)
  drawer.register({ id = "test.log", label = "Test", limit = 3 })
  h.equal(pcall(drawer.register, { id = "test.log" }), false)
  drawer.append("test.log", { "one", "two\nthree", { text = "four", level = "error" } })
  h.equal(pcall(drawer.append, "test.log", { "valid", { text = false } }), false)
  flush()
  h.equal(drawer.status().unread, 3)
  h.equal(drawer.status().errors, 1)
  drawer.open("test.log")
  h.equal(lines(), { "two", "three", "four" })
  h.equal(drawer.status().unread, 0)
end)

h.test("open fills the bottom width, preserves requested focus, attaches shared styling and returns focus", function()
  reset()
  vim.cmd("vsplit")
  local origin = api.nvim_get_current_win()
  local cmdheight, laststatus = vim.o.cmdheight, vim.o.laststatus
  drawer.register({ id = "test.log" })
  local win = drawer.open("test.log", { focus = false })
  h.equal(api.nvim_get_current_win(), origin)
  h.equal(api.nvim_win_get_width(win), vim.o.columns)
  h.equal(vim.wo[win].winfixheight, true)
  h.equal(panes.inspect(win).role, "log")
  h.equal(vim.o.cmdheight, cmdheight)
  h.equal(vim.o.laststatus, laststatus)
  h.equal(drawer.open("test.log"), win)
  h.equal(#api.nvim_tabpage_list_wins(0), 3)
  drawer.close()
  h.equal(api.nvim_get_current_win(), origin)
  h.equal(#api.nvim_tabpage_list_wins(0), 2)
end)

h.test("background appends follow without stealing focus, scrollback pauses and survives retention", function()
  reset()
  drawer.register({ id = "test.log", limit = 50 })
  drawer.append("test.log", log(50))
  local origin = api.nvim_get_current_win()
  local win = drawer.open("test.log", { focus = false })
  drawer.append("test.log", "line 51")
  flush()
  h.equal(api.nvim_get_current_win(), origin)
  h.equal(api.nvim_win_get_cursor(win)[1], 50)
  api.nvim_win_set_cursor(win, { 20, 0 })
  local reading = api.nvim_buf_get_lines(drawer.inspect().buffer, 19, 20, false)[1]
  drawer.append("test.log", "line 52")
  flush()
  h.equal(drawer.inspect().follow, false)
  h.contains(vim.wo[win].winbar, "Paused")
  local row = api.nvim_win_get_cursor(win)[1]
  h.equal(api.nvim_buf_get_lines(drawer.inspect().buffer, row - 1, row, false)[1], reading)
  h.equal(drawer.status().unread, 1)
  drawer.follow(true)
  h.equal(api.nvim_win_get_cursor(win)[1], 50)
  h.equal(drawer.status().unread, 0)
end)

h.test("filter uses literal text, leaves hidden unread entries, and clear is shared", function()
  reset()
  drawer.register({ id = "test.log" })
  drawer.append("test.log", { "a.b", "aXb", { text = "FAIL", level = "error" } })
  drawer.filter("A.B")
  drawer.open("test.log")
  h.equal(lines(), { "a.b" })
  h.equal(drawer.status().errors, 1)
  drawer.filter("")
  flush()
  h.equal(#lines(), 3)
  h.equal(drawer.status().unread, 0)
  drawer.clear()
  flush()
  h.equal(lines(), { "(no output)" })
  h.equal(drawer.providers()[1].count, 0)
end)

h.test("tabs remember independent source, height, filter and unread state", function()
  reset()
  drawer.register({ id = "test.first" })
  drawer.register({ id = "test.second" })
  drawer.append("test.first", "first")
  local first_tab = api.nvim_get_current_tabpage()
  local first_win = drawer.open("test.first")
  api.nvim_win_set_height(first_win, 5)
  drawer.close()
  drawer.open()
  h.equal(api.nvim_win_get_height(drawer.inspect().window), 5)
  vim.cmd("tabnew")
  local second_tab = api.nvim_get_current_tabpage()
  drawer.open("test.second")
  drawer.append("test.first", { text = "new", level = "error" })
  flush()
  h.equal(drawer.inspect(first_tab).selected, "test.first")
  h.equal(drawer.inspect(second_tab).selected, "test.second")
  h.equal(drawer.status(first_tab).unread, 1)
  h.equal(drawer.status(second_tab).unread, 2)
  h.truthy(drawer.inspect(first_tab).buffer ~= drawer.inspect(second_tab).buffer)
  api.nvim_set_current_tabpage(first_tab)
  flush()
  h.equal(drawer.status(first_tab).unread, 0)
  api.nvim_set_current_tabpage(second_tab)
  local buf = drawer.inspect().buffer
  vim.cmd("tabclose!")
  flush()
  h.equal(api.nvim_buf_is_valid(buf), false)
end)

h.test("manual close and buffer replacement recover without closing unrelated windows", function()
  reset()
  drawer.register({ id = "test.log" })
  local win = drawer.open("test.log")
  api.nvim_win_close(win, true)
  flush()
  h.equal(drawer.status().open, false)
  win = drawer.open()
  local replacement = api.nvim_create_buf(true, false)
  api.nvim_win_set_buf(win, replacement)
  drawer.close()
  h.truthy(api.nvim_win_is_valid(win))
  h.equal(api.nvim_win_get_buf(win), replacement)
  h.equal(vim.wo[win].winbar, "")
  h.equal(vim.wo[win].winfixheight, false)
  h.truthy(drawer.open() ~= win)
end)

h.test("unregister selects an available source and cleans up even if the drawer is the last window", function()
  reset()
  drawer.register({ id = "test.first" })
  drawer.register({ id = "test.second" })
  drawer.append("test.second", "second")
  drawer.open("test.first")
  drawer.unregister("test.first")
  flush()
  h.equal(drawer.inspect().selected, "test.second")
  h.equal(lines(), { "second" })
  h.equal(panes.inspect(drawer.inspect().window).id, "test.second")
  drawer.unregister("test.second")
  flush()
  h.equal(lines(), { "(no sources registered)" })
  vim.cmd("only!")
  drawer.close()
  h.equal(vim.bo.buftype, "")
  drawer.teardown()
end)

h.test("providers refresh only on explicit actions and errors leave cached content intact", function()
  reset()
  local calls, clears = 0, 0
  drawer.register({ id = "test.log", label = "100% logs", refresh = function()
    calls = calls + 1
    if calls == 3 then error("provider failed") end
    return { "snapshot " .. calls }
  end, clear = function() clears = clears + 1 end })
  drawer.open("test.log")
  h.equal(lines(), { "snapshot 1" })
  drawer.status(); drawer.inspect(); flush()
  h.equal(calls, 1)
  drawer.refresh(); flush()
  h.equal(lines(), { "snapshot 2" })
  h.equal(pcall(drawer.refresh), false)
  h.equal(lines(), { "snapshot 2" })
  drawer.clear(); flush()
  h.equal(clears, 1)
  local rendered = api.nvim_eval_statusline(vim.wo[drawer.inspect().window].winbar,
    { winid = drawer.inspect().window, use_winbar = true, maxwidth = 180 }).str
  h.contains(rendered, "100% logs")
end)

h.test("commands expose real Messages output and do not override global keys", function()
  reset()
  local before = api.nvim_get_keymap("n")
  require("ux_chrome.commands").setup()
  api.nvim_echo({ { "drawer fixture message" } }, true, {})
  vim.cmd("UXChromeDrawerOpen ux.chrome.messages")
  h.contains(table.concat(lines(), "\n"), "drawer fixture message")
  h.equal(api.nvim_get_keymap("n"), before)
  vim.cmd("UXChromeDrawerClose")
  h.equal(drawer.status().open, false)
end)

h.test("status renderer escapes labels, fits narrow widths and adds a click target", function()
  local renderer = require("ux_chrome.render.statusline")
  local ctx = { name = "file.lua", mode = "n", width = 160, drawer = { unread = 12, errors = 2 } }
  local wide = renderer.render(ctx, {})
  h.contains(wide.text, "Logs 12 !2")
  h.contains(wide.text, "%@v:lua.require'ux_chrome.drawer'.click@")
  h.equal(renderer.render(ctx, { ["statusline.show_drawer"] = false }).text:find("Logs", 1, true), nil)
  for width = 1, 160 do
    ctx.width = width
    h.truthy(renderer.render(ctx, {}).width <= width)
  end
end)

h.test("teardown discards queued updates and all drawer windows and buffers", function()
  reset()
  drawer.register({ id = "test.log" })
  local win = drawer.open("test.log")
  local buf = drawer.inspect().buffer
  drawer.append("test.log", "queued")
  assert(require("ux_chrome").teardown())
  flush()
  h.equal(api.nvim_win_is_valid(win), false)
  h.equal(api.nvim_buf_is_valid(buf), false)
  h.equal(drawer.providers(), {})
  h.equal(vim.fn.exists("#UXChromePanes"), 0)
end)

reset()
h.finish()
